sudo: required
language: cpp
dist: bionic

compiler:
  - gcc

matrix:
  include:

    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
    #- sudo apt-get purge nvidia-*
    #- sudo add-apt-repository ppa:graphics-drivers/ppa
    #- sudo apt-get update
    #- sudo apt install nvidia-driver-415

  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-drivers cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}


before_script:
    - sudo nvidia-smi
    - echo ${CUDA_HOME}
    - export CUDA_HOME=${CUDA_HOME}
    - make -w CDBG=-w

script:

  - ./Splotch6-generic splotch_tab.par
